# Generated by Django 5.1.2 on 2024-10-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_movie_genre_alter_movie_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='picture',
            field=models.ImageField(null=True, upload_to='movie_image'),
        ),
    ]
