# Generated by Django 5.1.4 on 2024-12-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Properity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('category_option', models.CharField(choices=[('House', 'House'), ('Flat', 'Flat'), ('Apartment', 'Apartment'), ('Villa', 'Villa'), ('Plot', 'Plot')], default='House', max_length=100)),
                ('bedroom_count', models.PositiveIntegerField()),
                ('squarefootage', models.PositiveIntegerField()),
            ],
        ),
    ]
