# Generated by Django 5.1.4 on 2024-12-11 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
